language: go

go:
  - 1.9.x

env:
  - MAKE_TASK=test
#  - MAKE_TASK=lint

before_install:
  - mkdir -p $GOPATH/bin
  - pwd
  - echo $GOPATH
  - go get github.com/onsi/ginkgo/ginkgo
  - go install github.com/onsi/ginkgo/ginkgo

install:
  - make deps

script:
  - PATH="$PATH:$GOPATH/bin" make $MAKE_TASK
