---
groups:
- name: Master
  jobs:
  - master-test
  - master-lint
- name: Pull-request
  jobs:
  - pr-test
  - pr-lint

resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
  - name: boshspecs-master
    type: git
    source:
      uri: https://github.com/ahelal/boshspecs.git
      branch: master

  - name: golang
    type: docker-image
    source:
      repository: golang
      tag: "1.9"

  - name : boshspecs-pr
    type : pull-request
    source :
      access_token: ((github_token))
      repo : ahelal/boshspecs
      disable_forks: true

jobs:
  - name: master-test
    plan:
    - get: boshspecs-master
      trigger: true
    - get: golang

    - task: test
      input_mapping:
        boshspecs-repo: boshspecs-master
      image: golang
      file: boshspecs-master/ci/tasks/run-test.yml

  - name: master-lint
    plan:
    - get: boshspecs-master
      trigger: true
    - get: golang

    - task: lint
      input_mapping:
        boshspecs-repo: boshspecs-master
      image: golang
      file: boshspecs-master/ci/tasks/run-lint.yml


  - name: pr-test
    plan:
    - get: boshspecs-pr
      version: every
      trigger: true
    - get: golang

    - task: run-test
      input_mapping:
        boshspecs-repo: boshspecs-pr
      image: golang
      file: boshspecs-pr/ci/tasks/run-test.yml

  - name: pr-lint
    plan:
    - get: boshspecs-pr
      version: every
      trigger: true
    - get: golang

    - task: lint
      input_mapping:
        boshspecs-repo: boshspecs-pr
      image: golang
      file: boshspecs-pr/ci/tasks/run-lint.yml